# Generated by Django 4.1 on 2022-08-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_product_category_product_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=1000, null=True),
        ),
    ]
