# Generated by Django 4.1 on 2022-09-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_progile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='progile_pic',
            new_name='profile_pic',
        ),
    ]
